In [1]:
#1. K-Means Clustering
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])

kmeans = KMeans(n_clusters=2, random_state=0)
kmeans.fit(X)

print("Labels:", kmeans.labels_)
print("Centroids:", kmeans.cluster_centers_)

Labels: [1 1 1 0 0 0]
Centroids: [[10.  2.]
 [ 1.  2.]]


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [2]:
#2. Hierarchical Clustering
from sklearn.cluster import AgglomerativeClustering
import numpy as np

X = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])

model = AgglomerativeClustering(n_clusters=2)
labels = model.fit_predict(X)

print(labels)

[1 1 1 0 0 0]


In [3]:
#3.DBSCAN (Density-Based Clustering)
from sklearn.cluster import DBSCAN
import numpy as np

X = np.array([[1,2],[2,2],[2,3],[8,7],[8,8],[25,80]])

db = DBSCAN(eps=3, min_samples=2)
labels = db.fit_predict(X)

print(labels)

[ 0  0  0  1  1 -1]


In [4]:
#4. Mean Shift Clustering
from sklearn.cluster import MeanShift
import numpy as np

X = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])

model = MeanShift()
labels = model.fit_predict(X)

print(labels)

[4 3 5 1 0 2]


In [5]:
#5.5. Gaussian Mixture Model (GMM)
from sklearn.mixture import GaussianMixture
import numpy as np

X = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])

gmm = GaussianMixture(n_components=2)
gmm.fit(X)

labels = gmm.predict(X)
print(labels)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


[0 0 0 1 1 1]


In [ ]:
#6. OPTICS
from sklearn.cluster import OPTICS

model = OPTICS(min_samples=2)
labels = model.fit_predict(X)

print(labels)

[0 0 0 1 1 1]


In [ ]:
#7. Birch Clustering
from sklearn.cluster import Birch

model = Birch(n_clusters=2)
labels = model.fit_predict(X)

print(labels)

[1 1 1 0 0 0]


In [ ]:
#8.Affinity Propagation
from sklearn.cluster import AffinityPropagation

model = AffinityPropagation()
labels = model.fit_predict(X)

print(labels)

[0 0 0 1 1 1]


In [12]:
#9.SPECTRAL CLUSTERING

import numpy as np
from sklearn.cluster import SpectralClustering

X = np.array([
    [1,2],
    [1,4],
    [1,0],
    [10,2],
    [10,4],
    [10,0]
])

model = SpectralClustering(
    n_clusters=2,
    affinity='nearest_neighbors',
    n_neighbors=2,   # important fix
    random_state=0
)

labels = model.fit_predict(X)

print(labels)

[0 0 0 1 1 1]


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\manifold\_spectral_embedding.py:329: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
